name: Update Activity

on:
  workflow_dispatch:

jobs:
  run-assignment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run Assignment
        uses: platzi/assignment@v3
        with:
          gh-token: ${{ secrets.GH_TOKEN }}
