name: Practice Workflow

on:
  workflow_dispatch:

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Echo Hello
        run: echo "Hola Alvaro, estás ejecutando tu primer workflow!"
